# Generated by Django 5.1.6 on 2025-03-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="logs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("total_entries", models.IntegerField(default=0)),
                ("entries_processed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField()),
                ("http_method", models.CharField(max_length=10)),
                ("resource", models.TextField()),
                ("status_code", models.IntegerField()),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "page_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="log_analyzer.logfile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="log_analyze_timesta_8e1429_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="log_analyze_ip_addr_b03e47_idx"
                    ),
                    models.Index(
                        fields=["resource"], name="log_analyze_resourc_06d097_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="log_analyze_status__d35768_idx"
                    ),
                    models.Index(
                        fields=["country"], name="log_analyze_country_e4ddfc_idx"
                    ),
                    models.Index(
                        fields=["page_category"], name="log_analyze_page_ca_e3c5a5_idx"
                    ),
                ],
            },
        ),
    ]
