# Generated by Django 4.2 on 2025-03-21 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_analyzer', '0002_externaldatasource'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logentry',
            name='log_analyze_resourc_06d097_idx',
        ),
        migrations.RemoveField(
            model_name='externaldatasource',
            name='connection_string',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='city',
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='database',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='host',
            field=models.CharField(blank=True, help_text='Database host or API base URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='source_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mssql', 'Microsoft SQL Server'), ('api', 'REST API'), ('mongodb', 'MongoDB Atlas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='page_category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='resource',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='error_message',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='log_files/'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
