# Generated by Django 4.2 on 2025-03-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyzer', '0003_remove_logentry_log_analyze_resourc_06d097_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='mongodb_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
